services:
  osmo:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENABLE_DOCS: "${OSMO_ENABLE_DOCS:-false}"
    image: osmoweb-tools-osmo:latest
    container_name: osmoweb-tools-osmo
    init: true
    network_mode: host
    environment:
      OSMO_CFG_PATH: /etc/osmo
      OSMO_LOG_PATH: /var/log/osmo
      OSMO_INCLUDE_BTS: "${OSMO_INCLUDE_BTS:-false}"
      OSMO_TRX_DRIVER: "${OSMO_TRX_DRIVER:-}"
    volumes:
      - ${OSMO_HOST_CFG_PATH:-./osmo/config}:/etc/osmo
      - ${OSMO_HOST_LOG_PATH:-./osmo/logs}:/var/log/osmo
      - ${OSMO_HOST_DATA_PATH:-./osmo/data}:/usr/local/etc/osmocom
    restart: unless-stopped
